#!/bin/bash
clear
red='\e[1;31m';green='\e[0;32m';yellow='\e[0;33m';blue='\e[0;34m';magenta='\e[0;35m';cyan='\e[0;36m';bb='\e[0;94m';white='\e[0;37m';NC='\e[0m'

MYIP=$(wget -qO- icanhazip.com)
domain=$(cat /etc/xray/domain)
tls="$(cat ~/log-install.txt | grep -w "XRAY VLESS WS TLS" | cut -d: -f2 | sed 's/ //g')"
none="$(cat ~/log-install.txt | grep -w "XRAY VLESS WS NON TLS" | cut -d: -f2 | sed 's/ //g')"
xhttp="$(cat ~/log-install.txt | grep -w "XRAY VLESS XHTTP NON TLS" | cut -d: -f2 | sed 's/ //g')"
FILE="/usr/local/etc/xray/config.json"

grep "^### " $FILE 2>/dev/null | awk '{print $2" "$3}' | sort -u > /tmp/vless.list
NUMBER_OF_CLIENTS=$(wc -l < /tmp/vless.list)
if [[ $NUMBER_OF_CLIENTS -eq 0 ]]; then echo "No Expired User"; exit 1; fi

clear
echo -e "${bb}════════${NC}"
echo -e " ${cyan}CHECK XRAY VLESS CONFIG${bb} "
echo -e "${bb}════════${NC}"
echo ""
i=1
while read line; do
echo " $i) $line"
NAMES[$i]=$(echo $line | awk '{print $1}')
i=$((i+1))
done < /tmp/vless.list
echo ""
read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
user=${NAMES[$CLIENT_NUMBER]}
uuid=$(grep "email\": \"$user\"" "$FILE" | head -1 | cut -d '"' -f4)
exp=$(grep "$user" /tmp/vless.list | awk '{print $2}')

# GENERATE LINK
vlesslink1="vless://${uuid}@${domain}:${tls}?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:${none}?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:${none}?path=/vless&encryption=none&type=httpupgrade#${user}"
vlesslink4="vless://${uuid}@${domain}:${xhttp}?mode=auto&encryption=none&type=http&path=/xhttp#${user}"
vless_vision="vless://${uuid}@${domain}:${tls}?type=vision&security=tls&encryption=none#${user}"
vlessgrpc="vless://${uuid}@${domain}:${tls}?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
digiboost="vless://${uuid}@${domain}:${tls}?path=/digi-booster&security=tls&encryption=none&type=ws#${user}-DIGI-BOOST-3MB"
digiboost2="vless://${uuid}@${domain}:${tls}?path=/digi-booster2&security=tls&encryption=none&type=ws#${user}-DIGI-BOOST-6/12MB"
diginew="vless://${uuid}@${domain}:${tls}?path=/digi-new&security=tls&encryption=none&type=ws#${user}-DIGI-NEW"
maxisviu="vless://${uuid}@${domain}:${tls}?path=/maxis-viu&security=tls&encryption=none&type=ws#${user}-MAXIS-VIU"
maxisfrez="vless://${uuid}@${domain}:${xhttp}?mode=auto&encryption=none&type=http&path=/maxis-frez#${user}-MAXIS-FREZ"
umopayload2="vless://${uuid}@${domain}:${tls}?path=/umo-xlite&security=tls&encryption=none&type=ws#${user}-UMO-XLITE"
umopayload="vless://${uuid}@${domain}:${tls}?path=/umo-strx&security=tls&encryption=none&type=ws#${user}-UMO-STRX"
umobile3="vless://${uuid}@${domain}:${tls}?path=/umobile-ws&security=tls&encryption=none&type=ws#${user}-UMOBILE-WS"
yes="vless://${uuid}@${domain}:${tls}?path=/yes&security=tls&encryption=none&type=ws#${user}-YES4G"
yoodopubg1="vless://${uuid}@${domain}:${tls}?path=/yoodo-pubg&security=tls&encryption=none&type=ws#${user}-YOODO-PUBG"
yoodopokemon1="vless://${uuid}@${domain}:${tls}?path=/yoodo-pokemon&security=tls&encryption=none&type=ws#${user}-YOODO-POKEMON"
yoodoml1="vless://${uuid}@${domain}:${tls}?path=/yoodo-ml&security=tls&encryption=none&type=ws#${user}-YOODO-ML"
unifi1="vless://${uuid}@${domain}:${tls}?path=/unifi-wow&security=tls&encryption=none&type=ws#${user}-UNIFI-WOW"
unifi2="vless://${uuid}@${domain}:${tls}?path=/unifi-bebas&security=tls&encryption=none&type=ws#${user}-UNIFI-BEBAS"

clear
echo -e ""
echo -e "================================="
echo -e " XRAY VLESS WS & XTLS "
echo -e "================================="
echo -e "Remarks : ${user}"
echo -e "Expired : ${exp}"
echo -e "IP/Host : ${MYIP}"
echo -e "Domain : ${domain}"
echo -e "Port TLS : ${tls}"
echo -e "Port NTLS : ${none}"
echo -e "Port XHTTP : ${xhttp}"
echo -e "ID : ${uuid}"
echo -e "================================="
echo -e "LINK VLESS TLS :"
echo -e "\`\`\`"
echo -e "${vlesslink1}"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS NTLS : "
echo -e "\`\`"
echo -e "${vlesslink2}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "LINK VLESS HTTPUPGRADE : "
echo -e "\`\`\`"
echo -e "${vlesslink3}"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS XHTTP : "
echo -e "\`\`"
echo -e "${vlesslink4}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "LINK VLESS XTLS VISION : "
echo -e "\`\`\`"
echo -e "${vless_vision}"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS GRPC : "
echo -e "\`\`"
echo -e "${vlessgrpc}"
echo -e "\`\`\`"

echo -e " ${bb}═══════════════${NC} "
echo -e " \033[30;5;47m ⇱ TELCO CONFIG ⇲ \033[m"
echo -e " ${bb}═══════════════${NC} "
echo -e ""
echo -e "${cyan}LINK VLESS DIGI BOOSTER 3MBPS :${NC} "
echo -e "\`\`"
echo -e "${digiboost}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS DIGI BOOSTER 6/12MBPS :${NC} "
echo -e "\`\`"
echo -e "${digiboost2}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS DIGI TANPA LANGGAN :${NC} "
echo -e "\`\`"
echo -e "${diginew}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS MAXIS-VIU :${NC} "
echo -e "\`\`\`"
echo -e "${maxisviu}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS MAXIS-FREZ-XHTTP :${NC} "
echo -e "\`\`"
echo -e "${maxisfrez}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE PAYLOAD XLITE:${NC} "
echo -e "\`\`\`"
echo -e "${umopayload2}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE PAYLOAD STRX:${NC} "
echo -e "\`\`"
echo -e "${umopayload}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE WEBSOCKET:${NC} "
echo -e "\`\`\`"
echo -e "${umobile3}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YES4G :${NC} "
echo -e "\`\`\`"
echo -e "${yes}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO PUBG :${NC} "
echo -e "\`\`"
echo -e "${yoodopubg1}"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO POKEMON :${NC} "
echo -e "\`\`\`"
echo -e "${yoodopokemon1}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO ML :${NC} "
echo -e "\`\`\`"
echo -e "${yoodoml1}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UNIFI WOW:${NC} "
echo -e "\`\`"
echo -e "${unifi1}"
echo -e "\`\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UNIFI BEBAS:${NC} "
echo -e "\`\`\`"
echo -e "${unifi2}"
echo -e "\`\`"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "    SILA COPY LINK DI ATAS"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "TELCO :"
echo -e "Remarks : ${user}"
echo -e "Domain : ${domain}"
echo -e "AKTIF : Day"
echo -e "Created : $created" # <--- TAMBAH 2
echo -e "Expired : $exp"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "ID : ${uuid}"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "ScriptMod By khaiVPN"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
clear
menu
