#!/bin/bash
clear
red='\e[1;31m';green='\e[0;32m';yellow='\e[0;33m';blue='\e[0;34m';magenta='\e[0;35m';cyan='\e[0;36m';bb='\e[0;94m';white='\e[0;37m';NC='\e[0m'

MYIP=$(wget -qO- icanhazip.com)
dom=$(cat /etc/xray/domain)
sni=$(cat /etc/xray/domain)
path=""
tls="$(cat ~/log-install.txt | grep -w "XRAY VLESS WS TLS" | cut -d: -f2 | sed 's/ //g')"
none="$(cat ~/log-install.txt | grep -w "XRAY VLESS WS NON TLS" | cut -d: -f2 | sed 's/ //g')"
xhttp="$(cat ~/log-install.txt | grep -w "XRAY VLESS XHTTP NON TLS" | cut -d: -f2 | sed 's/ //g')"
FILE="/usr/local/etc/xray/config.json"

grep "^### " $FILE 2>/dev/null | awk '{print $2" "$3}' | sort -u > /tmp/vless.list
NUMBER_OF_CLIENTS=$(wc -l < /tmp/vless.list)
if [[ $NUMBER_OF_CLIENTS -eq 0 ]]; then echo "No Expired User"; exit 1; fi

clear
echo -e " ${bb}═══════════════════════${NC} "
echo -e " \033[30;5;47m CHECK XRAY VLESS CONFIG\033[m"
echo -e " ${bb}═══════════════════════${NC} "
echo ""
i=1
while read line; do
echo " $i) $line"
NAMES[$i]=$(echo $line | awk '{print $1}')
i=$((i+1))
done < /tmp/vless.list
echo ""
read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
user=${NAMES[$CLIENT_NUMBER]}
uuid=$(grep "email\": \"$user\"" "$FILE" | head -1 | cut -d '"' -f4)
exp=$(grep "$user" /tmp/vless.list | awk '{print $2}')

# LINK BIASA IKUT FORMAT KAU
vlesslink1="vless://${uuid}@${dom}:$tls?path=$path/xvless&security=tls&encryption=none&type=ws&sni=$sni#${user}"
vlesslink2="vless://${uuid}@${dom}:$none?path=$path/xvlessntls&encryption=none&type=ws&host=$sni#${user}"
vlesslink3="vless://${uuid}@${dom}:$none?path=$path/xvless-hup&encryption=none&type=httpupgrade&host=$sni#${user}"
vlesslink4="vless://${uuid}@$dom:$xhttp?mode=auto&path=$path/xvless-xhttp-ntls&encryption=none&type=xhttp&host=$dom#${user}"
vless_vision="vless://${uuid}@${dom}:$tls?security=tls&encryption=none&headerType=none&type=tcp&flow=xtls-rprx-vision&sni=$sni#$user"
vlessgrpc="vless://${uuid}@${dom}:$tls?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vlgrpc&sni=$sni#$user"

# LINK TELCO IKUT FORMAT KAU
digiboost="vless://${uuid}@162.159.133.61:$none?path=/xvlessntls&encryption=none&type=ws&host=cdn.opensignal.com.$dom#${user}-digi-boost-3mbps"
digiboost2="vless://${uuid}@opensignal.com.$dom:$none?path=/xvlessntls&encryption=none&type=ws#${user}-digi-boost-6/12mbps"
diginew="vless://${uuid}@172.66.169.187:$none?path=/xvlessntls&encryption=none&type=ws&host=speedtest.net.$dom#${user}-digi-new"
maxisviu="vless://${uuid}@help.viu.com.$dom:$none?path=/xvlessntls&encryption=none&type=ws&host=help.viu.com#${user}-maxis-viu"
maxisfrez="vless://${uuid}@auth.opensignal.com:$xhttp?mode=auto&path=$path/xvless-xhttp-ntls&encryption=none&type=xhttp&host=cdn.opensignal.$dom#${user}-max-frez"
umobile3="vless://${uuid}@172.66.40.170:$none?path=/xvlessntls&encryption=none&type=ws&host=$dom#${user}-umobile-ws"
umopayload="vless://${uuid}@auth.opensignal.com:$none?path=GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [host][crlf][crlf][split]CF-RAY / HTTP/1.1[crlf]Host: ${dom}[crlf]Upgrade: websocket[crlf][crlf]&encryption=none&type=ws&host=strx-payload://u.com.my/#${user}-umo-hp"
umopayload2="vless://${uuid}@auth.opensignal.com:$none?path=GET /cdn-cgi/trace HTTP/1.1[crlf]Host: u.com.my[crlf][crlf][split]CF-RAY /xvless-hup HTTP/1.1[crlf]Host: ${dom}[crlf]Upgrade: websocket[crlf][crlf]&encryption=none&type=httpupgrade&host=${dom}#${user}-umo-xlite"
yes="vless://${uuid}@104.17.147.22:$none?path=/vlessntls&encryption=none&type=ws&host=$dom#${user}-yes-router"
yoodopubg1="vless://${uuid}@${MYIP}:$none?path=$path/xvlessntls&encryption=none&type=ws&host=m.pubgmobile.com#${user}-yodoopubg1"
yoodopokemon1="vless://${uuid}@${MYIP}:$none?path=$path/xvlessntls&encryption=none&type=ws&host=community.pokemon.com#${user}-yodoopokemon1"
yoodoml1="vless://${uuid}@${MYIP}:$none?path=$path/xvlessntls&encryption=none&type=ws&host=m.mobilelegends.com#${user}-yodooml1"
unifi1="vless://${uuid}@auth.opensignal.com:$none?path=/xvlessntls&encryption=none&type=ws&host=$dom#${user}-unifi-wow"
unifi2="vless://${uuid}@104.17.10.12:$none?path=/xvlessntls&encryption=none&type=ws&host=$dom#${user}-unifi-bebas"

clear
echo -e ""
echo -e "================================="
echo -e " XRAY VLESS WS & XTLS "
echo -e "================================="
echo -e "Remarks : ${user}"
echo -e "Expired : ${exp}"
echo -e "IP/Host : ${MYIP}"
echo -e "Domain : ${dom}"
echo -e "Port TLS : ${tls}"
echo -e "Port NTLS : ${none}"
echo -e "Port XHTTP : ${xhttp}"
echo -e "ID : ${uuid}"
echo -e "================================="
echo -e "LINK VLESS TLS :"
echo -e "\`\`"
printf "%s\n" "$vlesslink1"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS NTLS : "
echo -e "\`\`"
printf "%s\n" "$vlesslink2"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS HTTPUPGRADE : "
echo -e "\`\`"
printf "%s\n" "$vlesslink3"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS XHTTP : "
echo -e "\`\`"
printf "%s\n" "$vlesslink4"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS XTLS VISION : "
echo -e "\`\`"
printf "%s\n" "$vless_vision"
echo -e "\`\`"
echo -e "================================="
echo -e "LINK VLESS GRPC : "
echo -e "\`\`"
printf "%s\n" "$vlessgrpc"
echo -e "\`\`"

echo -e " ${bb}═══════════════════════${NC} "
echo -e " \033[30;5;47m ⇱ TELCO CONFIG ⇲  \033[m"
echo -e " ${bb}═══════════════════════${NC} "
echo -e ""

echo -e "${cyan}LINK VLESS DIGI BOOSTER 3MBPS :${NC} "
echo -e "\`\`"
printf "%s\n" "$digiboost"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS DIGI BOOSTER 6/12MBPS :${NC} "
echo -e "\`\`"
printf "%s\n" "$digiboost2"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS DIGI TANPA LANGGAN :${NC} "
echo -e "\`\`"
printf "%s\n" "$diginew"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS MAXIS-VIU :${NC} "
echo -e "\`\`"
printf "%s\n" "$maxisviu"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS MAXIS-FREZ-XHTTP :${NC} "
echo -e "\`\`"
printf "%s\n" "$maxisfrez"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE PAYLOAD HP:${NC} "
echo -e "\`\`"
printf "%s\n" "$umopayload"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE PAYLOAD XLITE:${NC} "
echo -e "\`\`"
printf "%s\n" "$umopayload2"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UMOBILE WEBSOCKET:${NC} "
echo -e "\`\`"
printf "%s\n" "$umobile3"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YES ROUTER :${NC} "
echo -e "\`\`"
printf "%s\n" "$yes"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO PUBG :${NC} "
echo -e "\`\`"
printf "%s\n" "$yoodopubg1"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO POKEMON :${NC} "
echo -e "\`\`"
printf "%s\n" "$yoodopokemon1"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS YODOO ML :${NC} "
echo -e "\`\`"
printf "%s\n" "$yoodoml1"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UNIFI WOW:${NC} "
echo -e "\`\`"
printf "%s\n" "$unifi1"
echo -e "\`\`"
echo -e "================================="
echo -e "${cyan}LINK VLESS UNIFI BEBAS:${NC} "
echo -e "\`\`"
printf "%s\n" "$unifi2"
echo -e "\`\`"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "    SILA COPY LINK DI ATAS"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "TELCO :"
echo -e "Remarks : ${user}"
echo -e "Domain : ${dom}"
echo -e "AKTIF : Day"
#echo -e "Created : $created"
echo -e "Expired : $exp"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "ID : ${uuid}"
echo -e "◇━━━━━━━━━━━━━━━━━◇"
echo -e "ScriptMod By khaiVPN"
echo -e ""
read -n 1 -s -r -p "Press any key to back on menu"
clear
menu
